"""repository module

Revision ID: 2b08890419d6
Revises: 31091724d4af
Create Date: 2026-08-03 19:00:16.018188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b08890419d6'
down_revision: Union[str, Sequence[str], None] = '31091724d4af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('relative_path', sa.String(length=1000), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('extension', sa.String(length=20), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('category', sa.Enum('SOURCE', 'DOCUMENTATION', 'CONFIGURATION', 'BINARY', 'IGNORED', name='filecategory'), nullable=False),
    sa.Column('support_tier', sa.Enum('TIER_1', 'TIER_0', 'NONE', name='languagesupporttier'), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=True),
    sa.Column('is_binary', sa.Boolean(), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_repository_files_category', 'repository_files', ['category'], unique=False)
    op.create_index('ix_repository_files_language', 'repository_files', ['language'], unique=False)
    op.create_index(op.f('ix_repository_files_repository_id'), 'repository_files', ['repository_id'], unique=False)
    op.create_index('ix_repository_files_repository_relative_path', 'repository_files', ['repository_id', 'relative_path'], unique=True)
    op.add_column('repositories', sa.Column('primary_language', sa.String(length=100), nullable=True))
    op.add_column('repositories', sa.Column('primary_framework', sa.String(length=100), nullable=True))
    op.add_column('repositories', sa.Column('total_files', sa.Integer(), nullable=False))
    op.add_column('repositories', sa.Column('supported_files', sa.Integer(), nullable=False))
    op.add_column('repositories', sa.Column('skipped_files', sa.Integer(), nullable=False))
    op.add_column('repositories', sa.Column('repository_size', sa.Integer(), nullable=False))
    op.alter_column('repositories', 'github_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=False)
    op.alter_column('repositories', 'clone_path',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=False)
    op.alter_column('repositories', 'default_branch',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_unique_constraint(None, 'repositories', ['github_url'])
    op.drop_column('repositories', 'description')
    op.drop_column('repositories', 'last_indexed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('last_indexed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('repositories', sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'repositories', type_='unique')
    op.alter_column('repositories', 'default_branch',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('repositories', 'clone_path',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.alter_column('repositories', 'github_url',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.drop_column('repositories', 'repository_size')
    op.drop_column('repositories', 'skipped_files')
    op.drop_column('repositories', 'supported_files')
    op.drop_column('repositories', 'total_files')
    op.drop_column('repositories', 'primary_framework')
    op.drop_column('repositories', 'primary_language')
    op.drop_index('ix_repository_files_repository_relative_path', table_name='repository_files')
    op.drop_index(op.f('ix_repository_files_repository_id'), table_name='repository_files')
    op.drop_index('ix_repository_files_language', table_name='repository_files')
    op.drop_index('ix_repository_files_category', table_name='repository_files')
    op.drop_table('repository_files')
    # ### end Alembic commands ###
