"""add embeddings

Revision ID: 7524bb189201
Revises: ee4657f8f0b4
Create Date: 2026-09-05 14:47:40.102822

"""
from typing import Sequence, Union

from alembic import op
import pgvector
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '7524bb189201'
down_revision: Union[str, Sequence[str], None] = 'ee4657f8f0b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "embeddings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chunk_id", sa.Integer(), nullable=False),
        sa.Column("model", sa.String(length=255), nullable=False),
        sa.Column("dimensions", sa.Integer(), nullable=False),
        sa.Column(
            "embedding",
            pgvector.sqlalchemy.vector.VECTOR(dim=384),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["chunks.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "chunk_id",
            "model",
            name="uq_embedding_chunk_model",
        ),
    )

    op.create_index(
        op.f("ix_embeddings_chunk_id"),
        "embeddings",
        ["chunk_id"],
        unique=False,
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_embeddings_chunk_id"),
        table_name="embeddings",
    )
    op.drop_table("embeddings")
    # ### end Alembic commands ###