"""add chunks table

Revision ID: ee4657f8f0b4
Revises: 7c0d2f1a4b6e
Create Date: 2026-08-29 22:32:37.912827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee4657f8f0b4'
down_revision: Union[str, Sequence[str], None] = '7c0d2f1a4b6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_type', sa.Enum('MODULE', 'CLASS', 'FUNCTION', 'METHOD', 'IMPORT', 'VARIABLE', 'TEXT', name='chunktype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('symbol_name', sa.String(length=255), nullable=True),
    sa.Column('qualified_name', sa.String(length=1000), nullable=True),
    sa.Column('parent_symbol', sa.String(length=1000), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['repository_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id', 'chunk_index', name='uq_file_chunk_index')
    )
    op.create_index(op.f('ix_chunks_file_id'), 'chunks', ['file_id'], unique=False)
    op.create_index(op.f('ix_chunks_repository_id'), 'chunks', ['repository_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunks_repository_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_file_id'), table_name='chunks')
    op.drop_table('chunks')
    # ### end Alembic commands ###
